query TopographicPlace($query: String!) {
  topographicPlace(query: $query) {
    id
    name {
      value
    }
    parentTopographicPlace {
      name {
        value
      }
    }
    polygon {
      coordinates
    }
  }
}
